add store image
wecode-bootcamp-korea/siren-order-backend pull request #9
Opened 2019-07-22 08:34 UTC by ulfrid

# store model add_image urls
- 지점 정보에 지점사진 추가

2019-07-22 09:03 UTC, rampart81 requested changes

2019-07-22 09:03 UTC, rampart81 commented on store/models.py
> +    img_url = models.CharField(max_length=400, null=True)
`img_url` 이거 400글자면 충분 한가요?

2019-07-22 09:50 UTC, ulfrid commented on store/models.py
> +    img_url = models.CharField(max_length=400, null=True)
2500으로 수정했습니다

2019-07-24 02:31 UTC, rampart81 approved these changes
LGTM

2019-07-24 02:31 UTC, merged